language: generic
sudo: require
services:
  - docker

before_install:
  - docker build -t faroldesenvolvimento5/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true faroldesenvolvimento5/react-test npm test -- --coverage

after_success:
  - docker build -t faroldesenvolvimento5/multi-client ./client
  - docker build -t faroldesenvolvimento5/multi-nginx ./nginx
  - docker build -t faroldesenvolvimento5/multi-server ./server
  - docker build -t faroldesenvolvimento5/multi-worker ./worker
  #take the images to docker hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push faroldesenvolvimento5/multi-client
  - docker push faroldesenvolvimento5/multi-nginx
  - docker push faroldesenvolvimento5/multi-server
  - docker push faroldesenvolvimento5/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-us-east-1-260604202455"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY  